# Generated by Django 5.0.6 on 2024-05-15 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_alley_app', '0004_alter_customer_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Accounts',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
        migrations.AlterModelTable(
            name='accounts',
            table='Accounts',
        ),
    ]
