# Generated by Django 5.0.6 on 2024-05-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_alley_app', '0005_rename_customer_accounts_delete_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('productID', models.CharField(max_length=5)),
                ('item', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeID', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('employeeName', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=50)),
                ('role', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('employeeID', models.CharField(max_length=11)),
                ('employeeName', models.CharField(max_length=128)),
                ('totalSales', models.FloatField()),
                ('transactionDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=200)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('salesID', models.AutoField(primary_key=True, serialize=False)),
                ('orderID', models.IntegerField()),
                ('productID', models.CharField(max_length=11)),
                ('productName', models.CharField(max_length=128)),
                ('quantity', models.IntegerField()),
                ('total', models.FloatField()),
            ],
        ),
    ]
