# Generated by Django 4.2.5 on 2024-05-23 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_alley_app', '0006_currentorder_employee_orders_products_sales'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='products',
            table='products',
        ),
    ]
