# Generated by Django 5.0.6 on 2024-05-23 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_alley_app', '0007_alter_products_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='products',
            table=None,
        ),
    ]
